import { useState } from 'react';
import { DxcFlex, DxcTypography, DxcHeading, DxcButton, DxcTabs } from '@dxc-technology/halstack-react';
import { getSlaStatusColor, formatDateTime } from '../../data/mockData';
import './CaseView.css';

function CaseView({ caseData, onClose }) {
  const [activeTab, setActiveTab] = useState(0);

  const c = caseData;

  const getDocStatusColor = (status) => {
    switch (status) {
      case 'processed': return '#24A148';
      case 'processing': return '#0095FF';
      case 'uploaded': return '#FF6B00';
      case 'failed': return '#D0021B';
      default: return '#999';
    }
  };

  const getIntegrationStatusColor = (status) => {
    switch (status) {
      case 'Complete':
      case 'Sent': return '#24A148';
      case 'Partial': return '#FF6B00';
      case 'Failed': return '#D0021B';
      case 'Not Started': return '#999';
      default: return '#999';
    }
  };

  // Tab 1: Overview
  const renderOverview = () => (
    <div className="tab-content">
      <div className="info-grid">
        <InfoField label="Case / Submission reference" value={c.id} />
        <InfoField label="Channel" value={c.channel} />
        <InfoField label="Processing stage" value={c.processingStage} />
      </div>
      <div className="info-grid">
        <InfoField label="Source email subject" value={c.sourceEmailSubject} wide />
      </div>
      <div className="info-grid">
        <InfoField label="Source email sender" value={c.sourceEmailSender} />
        <InfoField label="Attachments (count)" value={String(c.attachmentCount)} />
      </div>
      <div className="info-grid">
        <InfoField label="MEA case reference" value={c.meaCaseRef} />
        <InfoField label="MEA case link" value={c.meaCaseLink} isLink />
        <InfoField label="DMS library address" value={c.dmsLibraryAddress} />
      </div>
    </div>
  );

  // Tab 2: Documents
  const renderDocuments = () => (
    <div className="tab-content">
      <DxcFlex direction="column" gap="var(--spacing-gap-s)">
        <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">
          DMS Library: {c.dmsLibraryAddress}
        </DxcTypography>
        <table className="data-table">
          <thead>
            <tr>
              <th>Document name</th>
              <th>Document type</th>
              <th>Status</th>
              <th>MEA doc ref</th>
              <th>Extraction status</th>
              <th>DMS doc ref</th>
              <th>DMS link</th>
            </tr>
          </thead>
          <tbody>
            {c.documents.map((doc, i) => (
              <tr key={i}>
                <td>
                  <DxcFlex gap="var(--spacing-gap-xs)" alignItems="center">
                    <span className="material-icons" style={{ fontSize: '16px', color: '#0095FF' }}>description</span>
                    {doc.name}
                  </DxcFlex>
                </td>
                <td>{doc.type || '\u2014'}</td>
                <td>
                  <span className="status-pill" style={{ backgroundColor: getDocStatusColor(doc.status) }}>
                    {doc.status}
                  </span>
                </td>
                <td>{doc.meaDocRef || '\u2014'}</td>
                <td>{doc.meaExtractionStatus || '\u2014'}</td>
                <td>{doc.dmsDocRef || '\u2014'}</td>
                <td>
                  {doc.dmsLink ? (
                    <a href={doc.dmsLink} className="link" target="_blank" rel="noopener noreferrer">Open</a>
                  ) : '\u2014'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </DxcFlex>
    </div>
  );

  // Tab 3: Timeline
  const renderTimeline = () => (
    <div className="tab-content">
      <table className="data-table">
        <thead>
          <tr>
            <th>Event type</th>
            <th>Description</th>
            <th>Source</th>
            <th>Date / Time</th>
            <th>Generated by</th>
          </tr>
        </thead>
        <tbody>
          {[...c.timeline].reverse().map((evt, i) => (
            <tr key={i}>
              <td>
                <DxcFlex gap="var(--spacing-gap-xs)" alignItems="center">
                  <span className="material-icons" style={{ fontSize: '16px', color: '#0095FF' }}>
                    {evt.eventType.includes('Created') ? 'add_circle' :
                     evt.eventType.includes('Assigned') ? 'person' :
                     evt.eventType.includes('Classification') ? 'label' :
                     evt.eventType.includes('Queue') ? 'swap_horiz' :
                     evt.eventType.includes('DMS') ? 'cloud_upload' :
                     evt.eventType.includes('SLA') ? 'timer' :
                     evt.eventType.includes('Document') ? 'attach_file' :
                     evt.eventType.includes('AO') ? 'send' : 'event'}
                  </span>
                  {evt.eventType}
                </DxcFlex>
              </td>
              <td>{evt.description}</td>
              <td>
                <span className={`source-badge source-${evt.source.toLowerCase()}`}>
                  {evt.source}
                </span>
              </td>
              <td>{formatDateTime(evt.dateTime)}</td>
              <td>{evt.generatedBy}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );

  // Tab 4: Classification
  const renderClassification = () => (
    <div className="tab-content">
      <div className="info-card">
        <div className="info-grid">
          <InfoField label="Classification status" value={c.classification.status} />
          <InfoField label="Transaction type (ABE Name)" value={c.classification.transactionType || '\u2014'} />
        </div>
        <div className="info-grid">
          <InfoField label="Classification timestamp" value={formatDateTime(c.classification.timestamp)} />
          <InfoField label="Classified by" value={c.classification.classifiedBy || '\u2014'} />
        </div>
        <div className="info-grid">
          <InfoField label="Notes / rationale" value={c.classification.notes || '\u2014'} wide />
        </div>
      </div>
    </div>
  );

  // Tab 5: Integrations
  const renderIntegrations = () => (
    <div className="tab-content">
      <DxcFlex direction="column" gap="var(--spacing-gap-m)">
        <div className="info-card">
          <DxcTypography fontWeight="font-weight-semibold" style={{ marginBottom: '12px' }}>AO Integration</DxcTypography>
          <div className="info-grid">
            <InfoField label="AO send status">
              <span className="status-pill" style={{ backgroundColor: getIntegrationStatusColor(c.integrations.aoSendStatus) }}>
                {c.integrations.aoSendStatus}
              </span>
            </InfoField>
            <InfoField label="AO last attempt date/time" value={formatDateTime(c.integrations.aoLastAttempt)} />
            <InfoField label="AO correlation ID" value={c.integrations.aoCorrelationId || '\u2014'} />
          </div>
        </div>
        <div className="info-card">
          <DxcTypography fontWeight="font-weight-semibold" style={{ marginBottom: '12px' }}>DMS Integration</DxcTypography>
          <div className="info-grid">
            <InfoField label="DMS send status">
              <span className="status-pill" style={{ backgroundColor: getIntegrationStatusColor(c.integrations.dmsSendStatus) }}>
                {c.integrations.dmsSendStatus}
              </span>
            </InfoField>
            <InfoField label="DMS last attempt date/time" value={formatDateTime(c.integrations.dmsLastAttempt)} />
          </div>
          {c.integrations.lastError && (
            <div className="error-summary">
              <span className="material-icons" style={{ fontSize: '16px', color: '#D0021B' }}>error_outline</span>
              <DxcTypography fontSize="font-scale-01">{c.integrations.lastError}</DxcTypography>
            </div>
          )}
        </div>
      </DxcFlex>
    </div>
  );

  // Tab 6: Admin
  const renderAdmin = () => (
    <div className="tab-content">
      <div className="info-card">
        <div className="info-grid">
          <InfoField label="Created by" value={c.admin.createdBy} />
          <InfoField label="Created date/time" value={formatDateTime(c.admin.createdDate)} />
        </div>
        <div className="info-grid">
          <InfoField label="Last updated date/time" value={formatDateTime(c.admin.lastUpdated)} />
          <InfoField label="Broker ID" value={c.brokerId} />
        </div>
        <div className="info-grid">
          <InfoField label="Internal Case ID" value={c.admin.internalIds.caseId} />
          <InfoField label="Workflow ID" value={c.admin.internalIds.workflowId} />
        </div>
        {c.admin.featureFlags.length > 0 && (
          <div className="info-grid">
            <InfoField label="Feature flags" value={c.admin.featureFlags.join(', ')} />
          </div>
        )}
        <div className="info-grid">
          <InfoField label="Environment">
            <span className="env-badge">{c.admin.environment}</span>
          </InfoField>
        </div>
      </div>
    </div>
  );

  const tabs = [
    { label: "Overview" },
    { label: "Documents" },
    { label: "Timeline" },
    { label: "Classification" },
    { label: "Integrations" },
    { label: "Admin" },
  ];

  const renderTabContent = () => {
    switch (activeTab) {
      case 0: return renderOverview();
      case 1: return renderDocuments();
      case 2: return renderTimeline();
      case 3: return renderClassification();
      case 4: return renderIntegrations();
      case 5: return renderAdmin();
      default: return renderOverview();
    }
  };

  // Progress bar width
  const progressStages = ['Ingestion', 'Classification', 'Validation', 'Fulfilment', 'Processing', 'Complete'];
  const currentStageIdx = progressStages.indexOf(c.processingStage);
  const progressPct = currentStageIdx >= 0 ? ((currentStageIdx + 1) / progressStages.length) * 100 : 10;

  return (
    <div className="case-view">
      {/* Header Strip */}
      <div className="case-header">
        <DxcFlex justifyContent="space-between" alignItems="center">
          <DxcFlex gap="var(--spacing-gap-m)" alignItems="center">
            <DxcHeading level={4} text={c.id} />
            <span className="sla-badge-lg" style={{ backgroundColor: getSlaStatusColor(c.slaStatus) }}>
              {c.slaStatus}
            </span>
          </DxcFlex>
          <DxcFlex gap="var(--spacing-gap-s)">
            <DxcButton label="Assign" mode="secondary" onClick={() => {}} />
            <DxcButton label="Hold" mode="secondary" onClick={() => {}} />
            <DxcButton label="Move to next stage" mode="primary" onClick={() => {}} />
          </DxcFlex>
        </DxcFlex>

        <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">
          Broker: {c.broker} &middot; Queue: {c.queue} &middot; Assignee: {c.assignee || 'Unassigned'}
        </DxcTypography>
      </div>

      {/* Progress Strip */}
      <div className="progress-strip">
        <DxcTypography fontWeight="font-weight-semibold" fontSize="font-scale-02">Case Progress</DxcTypography>
        <div className="progress-bar-container">
          <div className="progress-bar" style={{ width: `${progressPct}%` }} />
        </div>

        <div className="progress-fields">
          <div className="progress-field">
            <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">Classification status</DxcTypography>
            <DxcTypography fontWeight="font-weight-semibold">{c.classificationStatus}</DxcTypography>
          </div>
          <div className="progress-field">
            <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">Transaction type (ABE Name)</DxcTypography>
            <DxcTypography fontWeight="font-weight-semibold">{c.transactionType || '\u2014'}</DxcTypography>
          </div>
          <div className="progress-field">
            <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">SLA / Age</DxcTypography>
            <DxcTypography fontWeight="font-weight-semibold">{c.slaRemaining}</DxcTypography>
          </div>
          <div className="progress-field">
            <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">Received</DxcTypography>
            <DxcTypography fontWeight="font-weight-semibold">{formatDateTime(c.receivedDate)}</DxcTypography>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="case-tabs">
        <DxcTabs
          activeTabIndex={activeTab}
          onTabClick={(i) => setActiveTab(i)}
          tabs={tabs}
        />
      </div>

      {/* Tab Content */}
      {renderTabContent()}
    </div>
  );
}

// Reusable info field component
function InfoField({ label, value, isLink, wide, children }) {
  return (
    <div className={`info-field ${wide ? 'info-field-wide' : ''}`}>
      <DxcTypography fontSize="font-scale-01" color="var(--color-fg-neutral-stronger)">{label}</DxcTypography>
      {children ? children : (
        isLink && value && value !== '\u2014' ? (
          <a href={value} className="link" target="_blank" rel="noopener noreferrer">
            Open MEA case
          </a>
        ) : (
          <DxcTypography fontWeight="font-weight-semibold">{value || '\u2014'}</DxcTypography>
        )
      )}
    </div>
  );
}

export default CaseView;
